<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <Description>
            Provides multitenancy middleware
        </Description>
        <PackageTags>elsa module multitenancy</PackageTags>
    </PropertyGroup>

    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="D:\repos\elsa-core-main\src\modules\Elsa.Http\Elsa.Http.csproj" />
        <ProjectReference Include="D:\repos\elsa-core-main\src\modules\Elsa.Tenants\Elsa.Tenants.csproj" />
    </ItemGroup>

</Project>
