<Project Sdk="Microsoft.NET.Sdk.Web">

    <ItemGroup>
		<ProjectReference Include="D:\repos\elsa-core-main\src\modules\Elsa.Caching\Elsa.Caching.csproj" />
		<ProjectReference Include="D:\repos\elsa-core-main\src\modules\Elsa.Common\Elsa.Common.csproj" />
		<ProjectReference Include="D:\repos\elsa-core-main\src\modules\Elsa.Expressions\Elsa.Expressions.csproj" />
		<ProjectReference Include="D:\repos\elsa-core-main\src\modules\Elsa.Workflows.Core\Elsa.Workflows.Core.csproj" />
		<ProjectReference Include="D:\repos\elsa-core-main\src\modules\Elsa.Workflows.Runtime\Elsa.Workflows.Runtime.csproj" />
		<ProjectReference Include="D:\repos\elsa-core-main\src\modules\Elsa\Elsa.csproj" />
		<ProjectReference Include="D:\repos\elsa-core-main\src\modules\Elsa.Expressions.CSharp\Elsa.Expressions.CSharp.csproj" />
		<ProjectReference Include="D:\repos\elsa-core-main\src\modules\Elsa.Expressions.JavaScript\Elsa.Expressions.JavaScript.csproj" />
		<ProjectReference Include="D:\repos\elsa-core-main\src\modules\Elsa.Expressions.Liquid\Elsa.Expressions.Liquid.csproj" />
		<ProjectReference Include="D:\repos\elsa-core-main\src\modules\Elsa.Expressions.Python\Elsa.Expressions.Python.csproj" />
		<ProjectReference Include="D:\repos\elsa-core-main\src\modules\Elsa.Http\Elsa.Http.csproj" />
		<ProjectReference Include="D:\repos\elsa-core-main\src\modules\Elsa.Identity\Elsa.Identity.csproj" />
		<ProjectReference Include="D:\repos\elsa-core-main\src\modules\Elsa.Tenants.AspNetCore\Elsa.Tenants.AspNetCore.csproj" />
		<ProjectReference Include="D:\repos\elsa-core-main\src\modules\Elsa.Workflows.Api\Elsa.Workflows.Api.csproj" />
    </ItemGroup>

	<ItemGroup>
      <Folder Include="App_Data\" />
    </ItemGroup>

</Project>
